//PRODUCTS ACTIONS TYPES
export const PRODUCT_START = "PRODUCT_START";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
/** Product Search actions types */
export const PRODUCT_SEARCH_START = "PRODUCT_SEARCH_START";
export const PRODUCT_SEARCH_RESET = "PRODUCT_SEARCH_RESET";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCESS";

// Product Update actions types
export const PRODUCT_UPDATE_START = "PRODUCT_UPDATE_START";
export const PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCESS";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

// Product Rating Top actions types
export const PRODUCT_RATING_TOP_START = "PRODUCT_RATING_TOP_START";
export const PRODUCT_RATING_TOP_ERROR = "PRODUCT_RATING_TOP_ERROR";
export const PRODUCT_RATING_TOP_SUCCESS = "PRODUCT_RATING_TOP_SUCESS";

// Product Create actions types
export const PRODUCT_CREATE_START = "PRODUCT_CREATE_START";
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCESS";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

// Product Create Review actions types
export const PRODUCT_CREATE_REVIEW_ERROR = "PRODUCT_CREATE_REVIEW_ERROR";
export const PRODUCT_CREATE_REVIEW_START = "PRODUCT_CREATE_REVIEW_START";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCESS";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

//NOTIFICATION ACTIONS TYPES
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

//CART ACTIONS TYPES
export const CART_ITEM_REMOVE = "CART_ITEM_REMOVE";
export const CART_ITEM_RESET = "CART_ITEM_RESET";
export const CART_ITEM_ADD = "CART_ITEM_ADD";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

//USER ACTIONS TYPES
/** Logging actions types */
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
/** Register actions types */
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
/** User Details actions types */
export const USER_DETAILS_START = "USER_DETAILS_START";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";
/** User Lists actions types */
export const USER_LIST_START = "USER_LIST_START";
export const USER_LIST_ERROR = "USER_LIST_ERROR";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
/** User Edit actions types */
export const USER_EDIT_START = "USER_EDIT_START";
export const USER_EDIT_ERROR = "USER_EDIT_ERROR";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
/** User Update actions types */
export const USER_UPDATE_START = "USER_UPDATE_START";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCESS";
/** User Update Profile actions types */
export const USER_UPDATE_PROFILE_START = "USER_UPDATE_PROFILE_START";
export const USER_UPDATE_PROFILE_ERROR = "USER_UPDATE_PROFILE_ERROR";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

//ORDERS ACTIONS TYPES
export const ORDER_START = "ORDER_START";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";

//ORDERS LIST ACTIONS TYPES
export const ORDER_LIST_START = "ORDER_LIST_START";
export const ORDER_LIST_ERROR = "ORDER_LIST_ERROR";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";

//ORDERS_PAY ACTIONS TYPES
export const ORDERS_PAY_START = "ORDERS_PAY_START";
export const ORDERS_PAY_ERROR = "ORDERS_PAY_ERROR";
export const ORDERS_PAY_SUCCESS = "ORDERS_PAY_SUCCESS";
export const ORDERS_PAY_RESET = "ORDERS_PAY_RESET";

//ORDERS_DELIVER ACTIONS TYPES
export const ORDERS_DELIVER_START = "ORDERS_DELIVER_START";
export const ORDERS_DELIVER_ERROR = "ORDERS_DELIVER_ERROR";
export const ORDERS_DELIVER_SUCCESS = "ORDERS_DELIVER_SUCCESS";
export const ORDERS_DELIVER_RESET = "ORDERS_DELIVER_RESET";

//USER_ORDERS ACTIONS TYPES
export const USER_ORDERS_START = "USER_ORDERS_START";
export const USER_ORDERS_ERROR = "USER_ORDERS_ERROR";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_RESET = "USER_ORDERS_RESET";
